services:
  - type: web
    name: fi-mcp-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: Final
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: GO_ENV
        value: production
    autoDeploy: true